name: Clojure CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: mkdir /tmp/sass
    - run: echo "/tmp/sass/dart_sass" >> $GITHUB_PATH
    - run: wget -c https://github.com/sass/dart-sass/releases/download/1.35.1/dart-sass-1.35.1-macos-x64.tar.gz -O /tmp/sass.tgz
    - run: tar -xzf /tmp/sass.tgz -C /tmp/sass
    
      
    - name: Generate Static Site
      run: lein run
