name: Cryogen Build & Deploy to GitHub Pages

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir /tmp/sass
      - run: wget -c https://github.com/sass/dart-sass/releases/download/1.35.1/dart-sass-1.35.1-linux-x64.tar.gz -O /tmp/sass.tgz
      - run: tar -xzf /tmp/sass.tgz -C /tmp/sass
      - run: /tmp/sass/dart-sass/sass --version


      - name: Generate Static Site
        run: lein with-profile prod run

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public